# -*- coding: utf-8 -*-
"""課題1-2:nl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ssaOEqMEY8an-63g6xeIkwF_wTy3c49O
"""

from google.colab import files
files.upload()

myfile = open('nl_read.txt')
lines = myfile.read()
lines

for count, line in enumerate(lines.split('\n')):
    print(f'{count}: {line}')

